In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\nishan\anaconda3\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\nishan\anaconda3\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\nishan\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\nishan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\nishan\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\nishan\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
print(pd.__version__)

2.3.3

### Series

In [3]:
data = [101,102,103,104,105]

Series = pd.Series(data,index=["A","B","C","D","E"])
print(Series)

A    101
B    102
C    103
D    104
E    105
dtype: int64

In [4]:
print(Series.loc["C"])
print(Series.iloc[4])

103
105

In [5]:
print(Series[Series >= 103])

C    103
D    104
E    105
dtype: int64

In [6]:
Calories = {'MON': 1750 , 'TUE': 1700 , 'WED': 1800 , 'THUR' : 2500 , 'FRI': 1850}
print(pd.Series(Calories))

MON     1750
TUE     1700
WED     1800
THUR    2500
FRI     1850
dtype: int64

In [7]:
series = pd.Series(Calories)
print(series.loc['MON'])
print(series.loc['TUE'])
print(series.loc['WED'])
print(series.loc['THUR'])

1750
1700
1800
2500

### DataFrame

In [8]:
Df = {"Name" : ['Nishan','Surya','Vishal'],
      "Age" : [23,22,23]}
Dataframe = pd.DataFrame(Df,index = ["Emp1","Emp2","Emp3"]);
print(Dataframe)

        Name  Age
Emp1  Nishan   23
Emp2   Surya   22
Emp3  Vishal   23

In [9]:
print(Dataframe.loc['Emp2'])

Name    Surya
Age        22
Name: Emp2, dtype: object

In [10]:
print(Dataframe.iloc[0])

Name    Nishan
Age         23
Name: Emp1, dtype: object

#### Adding to the DataFrames

In [11]:
Dataframe['Department'] = ['IT', 'SBA' , 'Portal']
Dataframe

        Name  Age Department
Emp1  Nishan   23         IT
Emp2   Surya   22        SBA
Emp3  Vishal   23     Portal

In [12]:
new_row = pd.DataFrame([{"Name":'Vidhya',"Age":23,"Department":'Finance Portal'},
                       { "Name":'Arun',"Age":25,"Department":'HR Portal'}], index = ['Emp4','Emp5'])
pd.concat([Dataframe,new_row])

        Name  Age      Department
Emp1  Nishan   23              IT
Emp2   Surya   22             SBA
Emp3  Vishal   23          Portal
Emp4  Vidhya   23  Finance Portal
Emp5    Arun   25       HR Portal

### Improting Files

In [13]:
df = pd.read_csv('Data.csv')
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [14]:
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass    Poison     0.7     6.9          0
1      2     Ivysaur     Grass    Poison     1.0    13.0          0
2      3    Venusaur     Grass    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       Bug       NaN     0.3     2.9          0
10    11     Metapod       Bug       NaN     0.7     9.9          0
11    12  Butterfree       Bug    Flying     1.1    32.0          0
12    13      Weedle       Bug    Poison     0.3     3.2          0
13    14      Kakuna       Bug    Poison     0.6    10.0          0
14    15    Beedrill       Bug    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       NaN     0.3     3.5          0
19    20    Raticate    Normal       NaN     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       NaN     2.0     6.9          0
23    24       Arbok    Poison       NaN     3.5    65.0          0
24    25     Pikachu  Electric       NaN     0.4     6.0          0
25    26      Raichu  Electric       NaN     0.8    30.0          0
26    27   Sandshrew    Ground       NaN     0.6    12.0          0
27    28   Sandslash    Ground       NaN     1.0    29.5          0
28    29    Nidoran♀    Poison       NaN     0.4     7.0          0
29    30    Nidorina    Poison       NaN     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       NaN     0.5     9.0          0
32    33    Nidorino    Poison       NaN     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       NaN     0.6     7.5          0
35    36    Clefable     Fairy       NaN     1.3    40.0          0
36    37      Vulpix      Fire       NaN     0.6     9.9          0
37    38   Ninetales      Fire       NaN     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     Grass    Poison     0.5     5.4          0
43    44       Gloom     Grass    Poison     0.8     8.6          0
44    45   Vileplume     Grass    Poison     1.2    18.6          0
45    46       Paras       Bug     Grass     0.3     5.4          0
46    47    Parasect       Bug     Grass     1.0    29.5          0
47    48     Venonat       Bug    Poison     1.0    30.0          0
48    49    Venomoth       Bug    Poison     1.5    12.5          0
49    50     Diglett    Ground       NaN     0.2     0.8          0
50    51     Dugtrio    Ground       NaN     0.7    33.3          0
51    52      Meowth    Normal       NaN     0.4     4.2          0
52    53     Persian    Normal       NaN     1.0    32.0          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
55    56      Mankey  Fighting       NaN     0.5    28.0          0
56    57    Primeape  Fighting       NaN     1.0    32.0          0
57    58   Growlithe      Fire       NaN     0.7    19.0          0
58    59    Arcanine      Fire       NaN     1.9   155.0          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       NaN     0.9    19.5          0
63    64     Kadabra   Psychic       NaN     1.3    56.5          0
64    65    Alakazam   Psychic       NaN     1.5    48.0          0
65    66      Machop  Fighting       NaN     0.8    19.5          0
66    67     Machoke  Fighting       NaN     1.5    70.5          0
67    68     Machamp  Fighting       NaN     1.6   130.0          0
68    69  Bellsprout     Grass    Poison     0.7     4.0          0
69    70  Weepinbell     Grass    Poison     1.0     6.4          0
70    71  Victreebel     Grass    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       NaN     1.0    30.0          0
77    78    Rapidash      Fire       NaN     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       NaN     0.9    30.0          0
88    89         Muk    Poison       NaN     1.2    30.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       NaN     1.0    32.4          0
96    97       Hypno   Psychic       NaN     1.6    75.6          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
99   100     Voltorb  Electric       NaN     0.5    10.4          0
100  101   Electrode  Electric       NaN     1.2    66.6          0
101  102   Exeggcute     Grass   Psychic     0.4     2.5          0
102  103   Exeggutor     Grass   Psychic     2.0   120.0          0
103  104      Cubone    Ground       NaN     0.4     6.5          0
104  105     Marowak    Ground       NaN     1.0    45.0          0
105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
107  108   Lickitung    Normal       NaN     1.2    65.5          0
108  109     Koffing    Poison       NaN     0.6     1.0          0
109  110     Weezing    Poison       NaN     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       NaN     1.1    34.6          0
113  114     Tangela     Grass       NaN     1.0    35.0          0
114  115  Kangaskhan    Normal       NaN     2.2    80.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       Bug    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       NaN     1.1    30.0          0
125  126      Magmar      Fire       NaN     1.3    44.5          0
126  127      Pinsir       Bug       NaN     1.5    55.0          0
127  128      Tauros    Normal       NaN     1.4    88.4          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       NaN     0.3     4.0          0
132  133       Eevee    Normal       NaN     0.3     6.5          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
134  135     Jolteon  Electric       NaN     0.8    24.5          0
135  136     Flareon      Fire       NaN     0.9    25.0          0
136  137     Porygon    Normal       NaN     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       NaN     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       NaN     1.8     3.3          0
147  148   Dragonair    Dragon       NaN     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1

In [15]:
print(df['Name'])

0       Bulbasaur
1         Ivysaur
2        Venusaur
3      Charmander
4      Charmeleon
          ...
145       Moltres
146       Dratini
147     Dragonair
148     Dragonite
149        Mewtwo
Name: Name, Length: 150, dtype: object

### Selection

In [16]:
Sdf = pd.read_csv('Data.csv', index_col = 'Name')
print(Sdf)

             No    Type1   Type2  Height  Weight  Legendary
Name
Bulbasaur     1    Grass  Poison     0.7     6.9          0
Ivysaur       2    Grass  Poison     1.0    13.0          0
Venusaur      3    Grass  Poison     2.0   100.0          0
Charmander    4     Fire     NaN     0.6     8.5          0
Charmeleon    5     Fire     NaN     1.1    19.0          0
...         ...      ...     ...     ...     ...        ...
Moltres     146     Fire  Flying     2.0    60.0          1
Dratini     147   Dragon     NaN     1.8     3.3          0
Dragonair   148   Dragon     NaN     4.0    16.5          0
Dragonite   149   Dragon  Flying     2.2   210.0          0
Mewtwo      150  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [17]:
Sdf.loc['Charizard']

No                6
Type1          Fire
Type2        Flying
Height          1.7
Weight         90.5
Legendary         0
Name: Charizard, dtype: object

In [18]:
Sdf.loc['Pikachu',['Type1','Height','Weight']]

Type1     Electric
Height         0.4
Weight         6.0
Name: Pikachu, dtype: object

In [19]:
Pokemon = input("Enter a Pokemon Name : ")

try:
    print(Sdf.loc[Pokemon])
except KeyError:
    print(f'{Pokemon} is not found')

Enter a Pokemon Name :  pikachu

pikachu is not found

sdag is not found

### Filtering

In [20]:
tall_poke = df[df['Height'] >= 2]
tall_poke

      No        Name    Type1    Type2  Height  Weight  Legendary
2      3    Venusaur    Grass   Poison     2.0   100.0          0
22    23       Ekans   Poison      NaN     2.0     6.9          0
23    24       Arbok   Poison      NaN     3.5    65.0          0
94    95        Onix     Rock   Ground     8.8   210.0          0
102  103   Exeggutor    Grass  Psychic     2.0   120.0          0
114  115  Kangaskhan   Normal      NaN     2.2    80.0          0
129  130    Gyarados    Water   Flying     6.5   235.0          0
130  131      Lapras    Water      Ice     2.5   220.0          0
142  143     Snorlax   Normal      NaN     2.1   460.0          0
145  146     Moltres     Fire   Flying     2.0    60.0          1
147  148   Dragonair   Dragon      NaN     4.0    16.5          0
148  149   Dragonite   Dragon   Flying     2.2   210.0          0
149  150      Mewtwo  Psychic      NaN     2.0   122.0          1

In [21]:
Legend = df[(df['Legendary'] == 1) | ((df['Type1'] == 'Water') | (df['Type2'] == 'Water'))]
Legend

      No        Name     Type1     Type2  Height  Weight  Legendary
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1

### AGGREGATION

In [23]:
df

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire     NaN     0.6     8.5          0
4      5  Charmeleon     Fire     NaN     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon     NaN     1.8     3.3          0
147  148   Dragonair   Dragon     NaN     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 7 columns]

In [28]:
df.mean(numeric_only=True)

No           75.500000
Height        1.200000
Weight       46.231333
Legendary     0.026667
dtype: float64

In [36]:
Group = df.groupby('Type1')
Group['Height'].mean()

Type1
Bug         0.900000
Dragon      2.666667
Electric    0.855556
Fairy       0.950000
Fighting    1.185714
Fire        1.216667
Ghost       1.466667
Grass       1.083333
Ground      0.850000
Ice         1.550000
Normal      0.986364
Poison      1.221429
Psychic     1.371429
Rock        1.844444
Water       1.300000
Name: Height, dtype: float64

In [37]:
(Group.count())

          No  Name  Type2  Height  Weight  Legendary
Type1
Bug       12    12      9      12      12         12
Dragon     3     3      1       3       3          3
Electric   9     9      3       9       9          9
Fairy      2     2      0       2       2          2
Fighting   7     7      0       7       7          7
Fire      12    12      2      12      12         12
Ghost      3     3      3       3       3          3
Grass     12    12     11      12      12         12
Ground     8     8      2       8       8          8
Ice        2     2      2       2       2          2
Normal    22    22     10      22      22         22
Poison    14    14      4      14      14         14
Psychic    7     7      1       7       7          7
Rock       9     9      9       9       9          9
Water     28    28     10      28      28         28

### Data Cleaning

In [41]:
dfdrop = df.drop(columns = ['No'])
df
dfdrop

           Name    Type1   Type2  Height  Weight  Legendary
0     Bulbasaur    Grass  Poison     0.7     6.9          0
1       Ivysaur    Grass  Poison     1.0    13.0          0
2      Venusaur    Grass  Poison     2.0   100.0          0
3    Charmander     Fire     NaN     0.6     8.5          0
4    Charmeleon     Fire     NaN     1.1    19.0          0
..          ...      ...     ...     ...     ...        ...
145     Moltres     Fire  Flying     2.0    60.0          1
146     Dratini   Dragon     NaN     1.8     3.3          0
147   Dragonair   Dragon     NaN     4.0    16.5          0
148   Dragonite   Dragon  Flying     2.2   210.0          0
149      Mewtwo  Psychic     NaN     2.0   122.0          1

[150 rows x 6 columns]

In [44]:
dfdropna = df.dropna(subset = ['Type2'])
dfdropna

      No        Name     Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur     Grass  Poison     0.7     6.9          0
1      2     Ivysaur     Grass  Poison     1.0    13.0          0
2      3    Venusaur     Grass  Poison     2.0   100.0          0
5      6   Charizard      Fire  Flying     1.7    90.5          0
11    12  Butterfree       Bug  Flying     1.1    32.0          0
..   ...         ...       ...     ...     ...     ...        ...
141  142  Aerodactyl      Rock  Flying     1.8    59.0          0
143  144    Articuno       Ice  Flying     1.7    55.4          1
144  145      Zapdos  Electric  Flying     1.6    52.6          1
145  146     Moltres      Fire  Flying     2.0    60.0          1
148  149   Dragonite    Dragon  Flying     2.2   210.0          0

[67 rows x 7 columns]

In [46]:
dffill = df.fillna({'Type2':'None'})
dffill

      No        Name    Type1   Type2  Height  Weight  Legendary
0      1   Bulbasaur    Grass  Poison     0.7     6.9          0
1      2     Ivysaur    Grass  Poison     1.0    13.0          0
2      3    Venusaur    Grass  Poison     2.0   100.0          0
3      4  Charmander     Fire    None     0.6     8.5          0
4      5  Charmeleon     Fire    None     1.1    19.0          0
..   ...         ...      ...     ...     ...     ...        ...
145  146     Moltres     Fire  Flying     2.0    60.0          1
146  147     Dratini   Dragon    None     1.8     3.3          0
147  148   Dragonair   Dragon    None     4.0    16.5          0
148  149   Dragonite   Dragon  Flying     2.2   210.0          0
149  150      Mewtwo  Psychic    None     2.0   122.0          1

[150 rows x 7 columns]

In [49]:
df['Type1'] = df['Type1'].replace({'Grass':'GRASS','Bug':'BUG'})
print(df.to_string())

      No        Name     Type1     Type2  Height  Weight  Legendary
0      1   Bulbasaur     GRASS    Poison     0.7     6.9          0
1      2     Ivysaur     GRASS    Poison     1.0    13.0          0
2      3    Venusaur     GRASS    Poison     2.0   100.0          0
3      4  Charmander      Fire       NaN     0.6     8.5          0
4      5  Charmeleon      Fire       NaN     1.1    19.0          0
5      6   Charizard      Fire    Flying     1.7    90.5          0
6      7    Squirtle     Water       NaN     0.5     9.0          0
7      8   Wartortle     Water       NaN     1.0    22.5          0
8      9   Blastoise     Water       NaN     1.6    85.5          0
9     10    Caterpie       BUG       NaN     0.3     2.9          0
10    11     Metapod       BUG       NaN     0.7     9.9          0
11    12  Butterfree       BUG    Flying     1.1    32.0          0
12    13      Weedle       BUG    Poison     0.3     3.2          0
13    14      Kakuna       BUG    Poison     0.6    10.0          0
14    15    Beedrill       BUG    Poison     1.0    29.5          0
15    16      Pidgey    Normal    Flying     0.3     1.8          0
16    17   Pidgeotto    Normal    Flying     1.1    30.0          0
17    18     Pidgeot    Normal    Flying     1.5    39.5          0
18    19     Rattata    Normal       NaN     0.3     3.5          0
19    20    Raticate    Normal       NaN     0.7    18.5          0
20    21     Spearow    Normal    Flying     0.3     2.0          0
21    22      Fearow    Normal    Flying     1.2    38.0          0
22    23       Ekans    Poison       NaN     2.0     6.9          0
23    24       Arbok    Poison       NaN     3.5    65.0          0
24    25     Pikachu  Electric       NaN     0.4     6.0          0
25    26      Raichu  Electric       NaN     0.8    30.0          0
26    27   Sandshrew    Ground       NaN     0.6    12.0          0
27    28   Sandslash    Ground       NaN     1.0    29.5          0
28    29    Nidoran♀    Poison       NaN     0.4     7.0          0
29    30    Nidorina    Poison       NaN     0.8    20.0          0
30    31   Nidoqueen    Poison    Ground     1.3    60.0          0
31    32    Nidoran♂    Poison       NaN     0.5     9.0          0
32    33    Nidorino    Poison       NaN     0.9    19.5          0
33    34    Nidoking    Poison    Ground     1.4    62.0          0
34    35    Clefairy     Fairy       NaN     0.6     7.5          0
35    36    Clefable     Fairy       NaN     1.3    40.0          0
36    37      Vulpix      Fire       NaN     0.6     9.9          0
37    38   Ninetales      Fire       NaN     1.1    19.9          0
38    39  Jigglypuff    Normal     Fairy     0.5     5.5          0
39    40  Wigglytuff    Normal     Fairy     1.0    12.0          0
40    41       Zubat    Poison    Flying     0.8     7.5          0
41    42      Golbat    Poison    Flying     1.6    55.0          0
42    43      Oddish     GRASS    Poison     0.5     5.4          0
43    44       Gloom     GRASS    Poison     0.8     8.6          0
44    45   Vileplume     GRASS    Poison     1.2    18.6          0
45    46       Paras       BUG     Grass     0.3     5.4          0
46    47    Parasect       BUG     Grass     1.0    29.5          0
47    48     Venonat       BUG    Poison     1.0    30.0          0
48    49    Venomoth       BUG    Poison     1.5    12.5          0
49    50     Diglett    Ground       NaN     0.2     0.8          0
50    51     Dugtrio    Ground       NaN     0.7    33.3          0
51    52      Meowth    Normal       NaN     0.4     4.2          0
52    53     Persian    Normal       NaN     1.0    32.0          0
53    54     Psyduck     Water       NaN     0.8    19.6          0
54    55     Golduck     Water       NaN     1.7    76.6          0
55    56      Mankey  Fighting       NaN     0.5    28.0          0
56    57    Primeape  Fighting       NaN     1.0    32.0          0
57    58   Growlithe      Fire       NaN     0.7    19.0          0
58    59    Arcanine      Fire       NaN     1.9   155.0          0
59    60     Poliwag     Water       NaN     0.6    12.4          0
60    61   Poliwhirl     Water       NaN     1.0    20.0          0
61    62   Poliwrath     Water  Fighting     1.3    54.0          0
62    63        Abra   Psychic       NaN     0.9    19.5          0
63    64     Kadabra   Psychic       NaN     1.3    56.5          0
64    65    Alakazam   Psychic       NaN     1.5    48.0          0
65    66      Machop  Fighting       NaN     0.8    19.5          0
66    67     Machoke  Fighting       NaN     1.5    70.5          0
67    68     Machamp  Fighting       NaN     1.6   130.0          0
68    69  Bellsprout     GRASS    Poison     0.7     4.0          0
69    70  Weepinbell     GRASS    Poison     1.0     6.4          0
70    71  Victreebel     GRASS    Poison     1.7    15.5          0
71    72   Tentacool     Water    Poison     0.9    45.5          0
72    73  Tentacruel     Water    Poison     1.6    55.0          0
73    74     Geodude      Rock    Ground     0.4    20.0          0
74    75    Graveler      Rock    Ground     1.0   105.0          0
75    76       Golem      Rock    Ground     1.4   300.0          0
76    77      Ponyta      Fire       NaN     1.0    30.0          0
77    78    Rapidash      Fire       NaN     1.7    95.0          0
78    79    Slowpoke     Water   Psychic     1.2    36.0          0
79    80     Slowbro     Water   Psychic     1.6    78.5          0
80    81   Magnemite  Electric     Steel     0.3     6.0          0
81    82    Magneton  Electric     Steel     1.0    60.0          0
82    83  Farfetch'd    Normal    Flying     0.8    15.0          0
83    84       Doduo    Normal    Flying     1.4    39.2          0
84    85      Dodrio    Normal    Flying     1.8    85.2          0
85    86        Seel     Water       NaN     1.1    90.0          0
86    87     Dewgong     Water       Ice     1.7   120.0          0
87    88      Grimer    Poison       NaN     0.9    30.0          0
88    89         Muk    Poison       NaN     1.2    30.0          0
89    90    Shellder     Water       NaN     0.3     4.0          0
90    91    Cloyster     Water       Ice     1.5   132.5          0
91    92      Gastly     Ghost    Poison     1.3     0.1          0
92    93     Haunter     Ghost    Poison     1.6     0.1          0
93    94      Gengar     Ghost    Poison     1.5    40.5          0
94    95        Onix      Rock    Ground     8.8   210.0          0
95    96     Drowzee   Psychic       NaN     1.0    32.4          0
96    97       Hypno   Psychic       NaN     1.6    75.6          0
97    98      Krabby     Water       NaN     0.4     6.5          0
98    99     Kingler     Water       NaN     1.3    60.0          0
99   100     Voltorb  Electric       NaN     0.5    10.4          0
100  101   Electrode  Electric       NaN     1.2    66.6          0
101  102   Exeggcute     GRASS   Psychic     0.4     2.5          0
102  103   Exeggutor     GRASS   Psychic     2.0   120.0          0
103  104      Cubone    Ground       NaN     0.4     6.5          0
104  105     Marowak    Ground       NaN     1.0    45.0          0
105  106   Hitmonlee  Fighting       NaN     1.5    49.8          0
106  107  Hitmonchan  Fighting       NaN     1.4    50.2          0
107  108   Lickitung    Normal       NaN     1.2    65.5          0
108  109     Koffing    Poison       NaN     0.6     1.0          0
109  110     Weezing    Poison       NaN     1.2     9.5          0
110  111     Rhyhorn    Ground      Rock     1.0   115.0          0
111  112      Rhydon    Ground      Rock     1.9   120.0          0
112  113     Chansey    Normal       NaN     1.1    34.6          0
113  114     Tangela     GRASS       NaN     1.0    35.0          0
114  115  Kangaskhan    Normal       NaN     2.2    80.0          0
115  116      Horsea     Water       NaN     0.4     8.0          0
116  117      Seadra     Water       NaN     1.2    25.0          0
117  118     Goldeen     Water       NaN     0.6    15.0          0
118  119     Seaking     Water       NaN     1.3    39.0          0
119  120      Staryu     Water       NaN     0.8    34.5          0
120  121     Starmie     Water   Psychic     1.1    80.0          0
121  122    Mr. Mime   Psychic     Fairy     1.3    54.5          0
122  123     Scyther       BUG    Flying     1.5    56.0          0
123  124        Jynx       Ice   Psychic     1.4    40.6          0
124  125  Electabuzz  Electric       NaN     1.1    30.0          0
125  126      Magmar      Fire       NaN     1.3    44.5          0
126  127      Pinsir       BUG       NaN     1.5    55.0          0
127  128      Tauros    Normal       NaN     1.4    88.4          0
128  129    Magikarp     Water       NaN     0.9    10.0          0
129  130    Gyarados     Water    Flying     6.5   235.0          0
130  131      Lapras     Water       Ice     2.5   220.0          0
131  132       Ditto    Normal       NaN     0.3     4.0          0
132  133       Eevee    Normal       NaN     0.3     6.5          0
133  134    Vaporeon     Water       NaN     1.0    29.0          0
134  135     Jolteon  Electric       NaN     0.8    24.5          0
135  136     Flareon      Fire       NaN     0.9    25.0          0
136  137     Porygon    Normal       NaN     0.8    36.5          0
137  138     Omanyte      Rock     Water     0.4     7.5          0
138  139     Omastar      Rock     Water     1.0    35.0          0
139  140      Kabuto      Rock     Water     0.5    11.5          0
140  141    Kabutops      Rock     Water     1.3    40.5          0
141  142  Aerodactyl      Rock    Flying     1.8    59.0          0
142  143     Snorlax    Normal       NaN     2.1   460.0          0
143  144    Articuno       Ice    Flying     1.7    55.4          1
144  145      Zapdos  Electric    Flying     1.6    52.6          1
145  146     Moltres      Fire    Flying     2.0    60.0          1
146  147     Dratini    Dragon       NaN     1.8     3.3          0
147  148   Dragonair    Dragon       NaN     4.0    16.5          0
148  149   Dragonite    Dragon    Flying     2.2   210.0          0
149  150      Mewtwo   Psychic       NaN     2.0   122.0          1